### PR TITLE
Support for modifying built-in prompt

### PR DESCRIPTION
**Pull request by k99k5**

### CODE REVIEW

**Comment by obiscr** [comment]
Thank you very much for your contribution, this is awesome.

I received a similar issue before, and my plan is to be able to extend this feature a bit more.

Three built-in Prompts could be added (currently there are only two). And support customization: name and Prompt.

For example, in the UI of OpenAISettingsPanel

image

Name：will be display in Mouse Prompt
Value：send to ai

I don't know if you are interested in completing it. Or also I can continue to improve it on top of your code.

**Comment by k99k5** [comment]
但是你上次不是说内置的不能加吗

**Comment by k99k5** [comment]
我这边自定义就够用了，这个暂时改不动了，复杂的可能你来弄会好点，



---Original---
From: ***@***.***&gt;
Date: Fri, May 5, 2023 09:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dromara/ChatGPT] Support for modifying built-in prompt (PR #217)




 
是的，我上次指的是实时更改，而且这里的修改完，必须重启才能生效的。不像自定义的Prompt。可以实时更新。

**Comment by obiscr** [comment]
之前的提交有bug，我就顺带一起修复了。：D

**Pull request merged**
